# Generated by Django 4.2.10 on 2024-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usd_rate", models.FloatField(default=0.0)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "errors",
                    models.CharField(blank=True, default="ALL OK", max_length=155),
                ),
            ],
        ),
    ]
